name: Mirror to Codeberg

on:
  workflow_call:
    secrets:
      CODEBERG_TOKEN:
        required: true

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch all branches
        run: git fetch --all

      - name: Push to Codeberg
        env:
          CODEBERG_TOKEN: ${{ secrets.CODEBERG_TOKEN }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          git remote add codeberg "https://voyagi:${CODEBERG_TOKEN}@codeberg.org/voyagi/${REPO_NAME}.git"
          git push codeberg --all --force
          git push codeberg --tags --force
